#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <math.h>
using namespace cv;
using namespace std;

/**
* A representation of the different types of blurs that can be used.
*
*/
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
/**
* liftTracker class.
* 
* Autogenerated Pipeline from GRIP
*
* Make sure to set sources before running process()
*/
class liftTracker {
	private:
		Mat source0;
		Mat blurOutput;
		Mat hsvThresholdOutput;
		Mat cvErodeOutput;
		vector<vector<Point> > findContoursOutput;
		vector<vector<Point> > filterContoursOutput;
		void blur(Mat &, BlurType &, double , Mat &);
		void hsvThreshold(Mat &, double [], double [], double [], Mat &);
		void cvErode(Mat &, Mat &, Point &, double , int , Scalar &, Mat &);
		void findContours(Mat &, bool , vector<vector<Point> > &);
		void filterContours(vector<vector<Point> > &, double , double , double , double , double , double , double [], double , double , double , double , vector<vector<Point> > &);

	public:
		liftTracker();
		void Process();
		void setsource0(Mat &source0);
		Mat* getblurOutput();
		Mat* gethsvThresholdOutput();
		Mat* getcvErodeOutput();
		vector<vector<Point> >* getfindContoursOutput();
		vector<vector<Point> >* getfilterContoursOutput();
};

